#!/usr/bin/env node
/**
 * check-links.cjs — relative-markdown-link resolvability linter (coherence track S2, DEC-DEV-0220).
 *
 * ── What it checks (Variant A — the ONLY thing, by measured verdict) ──
 * Markdown INLINE links `[label](target)` whose target is a RELATIVE path: does that path
 * resolve to a file or directory on disk (relative to the source file's directory)?
 *
 * ── What it deliberately does NOT check, and why (verdict is FINAL, not to be reopened) ──
 *   · Code-spans (`paths in backticks`). Measured precision 60%: forward-references ("the future
 *     `/ecosystem:upgrade`") are machine-indistinguishable from stale references. A 40%-false gate
 *     gets switched off and costs every future check — so backtick paths stay a human's job.
 *   · Anchors INSIDE a target file (`file.md#section`). v1 resolves the FILE only; the `#frag` is
 *     stripped and not verified. (A heading-slug checker is a separate, later mechanism.)
 *   · Reference-style link definitions (`[label]: url`) and bare autolinks — only `](…)` inline.
 * On the measuring run Variant A scored 93% precision (479 candidates → 14 hits, noise zonal),
 * which is why the excluded zones below are constants: the 7% noise was concentrated there.
 *
 * ── Excluded zones (constants, each with its reason) ── see EXCLUDE_* below.
 *
 * ── «ЧЕКЕР ОСЛЕП» ≠ «НАШЁЛ ДРЕЙФ» (the D4 law) ──
 * A link is a FINDING only when it was parsed AND its target was resolved AND the target is absent.
 * Any internal failure (an unreadable file, a crash) is NOT a broken link — the checker could not
 * LOOK. It screams a loud warning and exits 0. A gate has no right to fail on what it cannot know.
 *
 * ── Enforcement posture ──
 * STRICT by default (exit 1 on any broken link; each printed with file:line → target).
 * Kill-switch — MANDATORY on a shared-resource gate, so a half-fixed corpus in one session cannot
 * wedge everyone else's `npm run verify`:
 *   env LINK_CHECK_STRICT=0   or   flag --warn   → warn-only, exit 0.
 * (Same law as INVENTORY_SYNC_STRICT=0 / COUNTS_EXTENDED_STRICT=0.)
 *
 * Usage:
 *   node dev/meta-improvement/scripts/check-links.cjs            # strict (exit 1 on breakage)
 *   node dev/meta-improvement/scripts/check-links.cjs --warn     # warn-only (exit 0)
 *   node dev/meta-improvement/scripts/check-links.cjs --json     # machine-readable
 *
 * Wired into `npm run verify` as `check:links`.
 */

'use strict';

const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

function repoRoot() {
  try {
    return execSync('git rev-parse --show-toplevel', { encoding: 'utf8' }).trim();
  } catch (e) {
    return process.cwd();
  }
}

const ROOT = repoRoot();
const argv = process.argv.slice(2);
const JSON_MODE = argv.includes('--json');
const STRICT = !(argv.includes('--warn') || process.env.LINK_CHECK_STRICT === '0');

// ── Excluded zones (constants; each carries WHY it is exempt) ──────────────────
// Directory prefixes: any file whose repo-relative POSIX path starts with one of these is skipped.
const EXCLUDE_DIRS = [
  'dev/_archive/',        // archive — historical paths are validly bit-rotted; not a live contract.
  'dev/context-audit/',   // evidence corpora — 30 INTENTIONAL broken refs (the audit's own exhibits).
  'dev/coherence/',       // coherence-track evidence corpus — byte-exact old_string quotes carry paths as-they-WERE (that's their job).
  'dev/meta-improvement/audit-reports/',   // point-in-time session-audit snapshots — paths as-of-audit-day, rotated wholesale later.
  'dev/meta-improvement/patch-candidates/', // generated surface-only candidates (session-audit output) — snapshots, never navigation.
  'node_modules/',        // vendored deps — not our prose.
  '.git/',                // git internals.
  '.claude/worktrees/',   // sibling worktrees — another branch's tree, not this one's.
];
// Exact repo-relative files: append-only history legitimately references paths that later moved.
const EXCLUDE_FILES = [
  'DEV_JOURNAL.md',       // append-only developer history — old entries name paths as-they-were-then.
  'CHANGELOG.md',         // append-only consumer history — same rationale.
];
// Repo-relative file PATTERNS (same rationale class as EXCLUDE_FILES, but dated/rolling names).
const EXCLUDE_FILE_PATTERNS = [
  /^dev\/COHERENCE_AUDIT_[^/]*\.md$/, // audit registries — quote findings (incl. broken paths) verbatim as evidence.
];
// Targets that are GENERATED artifacts: legitimately absent in a fresh checkout / non-generating
// worktree, present after their generator runs. Absence is NOT rot — the link is the contract.
const GENERATED_TARGETS = new Set([
  'dev/meta-improvement/rails/RAILS.md', // regenerated by rails-session-start.js at SessionStart; gitignored.
]);

// Directory names never descended into during the walk (speed + the exclude semantics above).
const SKIP_DIRNAMES = new Set(['.git', 'node_modules']);

const toPosix = (p) => p.split(path.sep).join('/');

function isExcluded(relPosix) {
  if (EXCLUDE_FILES.includes(relPosix)) return true;
  if (EXCLUDE_FILE_PATTERNS.some((re) => re.test(relPosix))) return true;
  return EXCLUDE_DIRS.some((d) => relPosix === d.slice(0, -1) || relPosix.startsWith(d));
}

// ── Walk: gather every .md under ROOT, minus excluded zones ────────────────────
function gatherMarkdown() {
  const out = [];
  const walk = (absDir) => {
    let entries;
    try {
      entries = fs.readdirSync(absDir, { withFileTypes: true });
    } catch (e) {
      blind.push(`could not read directory ${toPosix(path.relative(ROOT, absDir))}: ${e.message}`);
      return;
    }
    for (const e of entries) {
      const abs = path.join(absDir, e.name);
      const rel = toPosix(path.relative(ROOT, abs));
      if (e.isDirectory()) {
        if (SKIP_DIRNAMES.has(e.name)) continue;
        if (isExcluded(rel + '/')) continue;
        walk(abs);
      } else if (e.name.toLowerCase().endsWith('.md')) {
        if (isExcluded(rel)) continue;
        out.push({ abs, rel });
      }
    }
  };
  walk(ROOT);
  return out;
}

// ── Link extraction ────────────────────────────────────────────────────────────
// Inline markdown link/image: `[label](target)` or `![alt](target)`. Captures the paren body;
// a following "title" and angle-bracket wrapping are stripped in normalizeTarget().
const LINK_RE = /!?\[[^\]]*\]\(([^)]+)\)/g;

// Returns the on-disk-checkable relative path, or null if this target is out of scope
// (external URL, pure anchor, absolute path, empty).
function normalizeTarget(raw) {
  let t = raw.trim();
  if (t.startsWith('<') && t.endsWith('>')) t = t.slice(1, -1).trim();
  // Drop a link title: `path "Title"` / `path 'Title'`. Title begins at the first whitespace
  // that precedes a quote; simplest robust rule — cut at the first unescaped whitespace.
  const wsCut = t.search(/\s/);
  if (wsCut !== -1) t = t.slice(0, wsCut);
  if (!t) return null;

  // External URLs, protocol-relative, and mail/other schemes — out of scope.
  if (/^(https?:|mailto:)/i.test(t)) return null;
  if (t.startsWith('//')) return null;                 // protocol-relative //host/…
  if (/^[a-z][a-z0-9+.-]*:\/\//i.test(t)) return null; // any scheme://

  // Pure anchor — same-document fragment, nothing to resolve on disk.
  if (t.startsWith('#')) return null;

  // Strip fragment and query — resolve the FILE, not the sub-target (v1: no in-file anchors).
  t = t.split('#')[0].split('?')[0];
  if (!t) return null;

  // Absolute paths — POSIX-absolute or Windows drive/UNC — are out of scope (v1: relative only).
  if (t.startsWith('/') || t.startsWith('\\')) return null;
  if (/^[a-zA-Z]:[\\/]/.test(t)) return null;

  // Template placeholders (`NOTE-<id>-<slug>.md`, `<reports-dir>/<uuid>.md`) — an instruction's
  // fill-in-the-blank, not a navigable path. Never resolvable by construction, so never a finding.
  if (t.includes('<') || t.includes('>')) return null;

  // Percent-decode (`%20` → space) so the disk lookup matches. Undecodable → use as-is.
  try { t = decodeURIComponent(t); } catch (e) { /* keep raw */ }

  return t || null;
}

// ── Findings + blind buckets ─────────────────────────────────────────────────
const findings = [];  // { file, line, target } — parsed, resolved, absent → GATES
const blind = [];     // could not look → NEVER gates
let filesScanned = 0;
let linksChecked = 0;

function scanFile(abs, rel) {
  let text;
  try {
    text = fs.readFileSync(abs, 'utf8');
  } catch (e) {
    blind.push(`could not read ${rel}: ${e.message}`);
    return;
  }
  filesScanned++;
  const srcDir = path.dirname(abs);
  const lines = text.split('\n');
  let inFence = false;
  lines.forEach((line, i) => {
    // Fenced code block = example output, not inventory/navigation (lesson 66) — skip wholesale.
    if (/^\s*(```|~~~)/.test(line)) { inFence = !inFence; return; }
    if (inFence) return;
    // Inline code spans (`[text](path)` shown as syntax) are examples too — blank them out.
    // Cost: a link whose LABEL contains a code span is also skipped (false-negative, acceptable;
    // a false-positive on every syntax example would get the gate switched off).
    const scannable = line.includes('`') ? line.replace(/`[^`]*`/g, '') : line;
    LINK_RE.lastIndex = 0;
    let m;
    while ((m = LINK_RE.exec(scannable)) !== null) {
      const target = normalizeTarget(m[1]);
      if (target === null) continue;
      linksChecked++;
      const resolved = path.resolve(srcDir, target);
      if (!fs.existsSync(resolved)) {
        const resolvedRel = toPosix(path.relative(ROOT, resolved));
        if (GENERATED_TARGETS.has(resolvedRel)) continue; // generated artifact — absence ≠ rot.
        findings.push({ file: rel, line: i + 1, target });
      }
    }
  });
}

// ── Main ─────────────────────────────────────────────────────────────────────
function main() {
  const files = gatherMarkdown();
  for (const { abs, rel } of files) scanFile(abs, rel);

  if (JSON_MODE) {
    process.stdout.write(JSON.stringify({
      ok: findings.length === 0,
      strict: STRICT,
      files_scanned: filesScanned,
      links_checked: linksChecked,
      findings,
      blind,
    }, null, 2) + '\n');
    return findings.length === 0 ? 0 : (STRICT ? 1 : 0);
  }

  const scope = `${filesScanned} .md files · ${linksChecked} relative markdown links`;

  if (blind.length) {
    process.stderr.write(`check-links: ⚠ ЧЕКЕР ОСЛЕП — ${blind.length} путь(и) НЕ проверен(ы):\n`);
    for (const b of blind) process.stderr.write(`  ${b}\n`);
    process.stderr.write('  Это НЕ битые ссылки — чекер не смог ПОСМОТРЕТЬ ⇒ не гейтит (blind exit 0).\n\n');
  }

  if (findings.length === 0) {
    process.stdout.write(`check-links: ✓ all relative markdown links resolve — ${scope}.\n`);
    process.stdout.write('  (scope: inline [](…) only; backtick paths & in-file anchors are NOT checked — see header.)\n');
    return 0;
  }

  process.stderr.write(`check-links: ${STRICT ? '✗' : '⚠'} BROKEN relative markdown links — ${findings.length} finding(s):\n\n`);
  for (const f of findings) {
    process.stderr.write(`  ${f.file}:${f.line}  →  ${f.target}\n`);
  }
  process.stderr.write(`\n  scope: ${scope}\n`);
  if (STRICT) {
    process.stderr.write('  Fix the target paths above (or the link), then re-run.\n');
    process.stderr.write('  Чужая незакрытая правка блокирует твой цикл? → LINK_CHECK_STRICT=0 npm run verify\n');
    return 1;
  }
  process.stderr.write('  (warn-only — exit 0. Strict is the default; this run was downgraded via --warn / LINK_CHECK_STRICT=0.)\n');
  return 0;
}

let code = 0;
try {
  code = main();
} catch (e) {
  // A checker that threw measured nothing. It may not assert breakage it never saw. Scream, don't gate.
  process.stderr.write(`check-links: ⚠ ЧЕКЕР УПАЛ — ${e.message}\n`);
  process.stderr.write('  Это НЕ битые ссылки: упавший чекер ничего не измерил ⇒ не гейтит (exit 0).\n');
  process.stderr.write('  Почини dev/meta-improvement/scripts/check-links.cjs.\n');
  code = 0;
}
process.exit(code);
